name: Update group judge status

on:
  workflow_dispatch:
  schedule:
  - cron: '*/3 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update group judge status
        run: |
          curl -G -L https://boj-group-judge-status-discord-bot.vercel.app/api/status \
          -d 'boj_token=${{ secrets.BOJ_TOKEN }}' \
          -d 'boj_group_code=${{ secrets.BOJ_GROUP_CODE }}' \
          -d 'discord_token=${{ secrets.DISCORD_TOKEN }}' \
          -d 'discord_guild_id=${{ secrets.DISCORD_GUILD_ID }}' \
          -d 'discord_channel_id=${{ secrets.DISCORD_CHANNEL_ID }}'
