name: Update group judge status

on:
  workflow_dispatch:
  schedule:
  - cron: '*/3 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update group judge status
        env:
          BOJ_TOKEN: ${{ secrets.BOJ_TOKEN }}
          BOJ_GROUP_CODE: ${{ secrets.BOJ_GROUP_CODE }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          curl --request POST \
          --url 'https://boj-group-judge-status-discord-bot.vercel.app/api/status?boj_token=${BOJ_TOKEN}&boj_group_code=${BOJ_GROUP_CODE}&discord_token=${DISCORD_TOKEN}&discord_guild_id=${DISCORD_GUILD_ID}&discord_channel_id=${DISCORD_CHANNEL_ID}'
